name: Build C# HelloWorld

on:
  push:
    paths:
      - 'HelloWorld/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'HelloWorld/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build ./HelloWorld/HelloWorld.csproj

      - name: Run HelloWorld and save output
        run: dotnet run --project ./HelloWorld/HelloWorld.csproj > output.txt

      - name: Assert output is exactly 'Hello, World!' (should succeed)
        shell: pwsh
        run: |
          $expected = "Hello, World!"
          $actual = Get-Content output.txt | Select-Object -First 1
          if ($actual -ne $expected) {
            Write-Error "Output was '$actual', expected '$expected'"
            exit 1
          }

      - name: Assert output is exactly 'Hello world' (should fail)
        shell: pwsh
        run: |
          $expected = "Hello world"
          $actual = Get-Content output.txt | Select-Object -First 1
          if ($actual -ne $expected) {
            Write-Error "Output was '$actual', expected '$expected'"
            exit 1
          }
