name: Build C# HelloWorld

on:
  push:
    paths:
      - 'HelloWorld/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'HelloWorld/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build ./HelloWorld/HelloWorld.csproj
